plugins {
    id 'base'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

tasks.named('build').configure {
    dependsOn(':fabric:build')
}

tasks.register('runClient') {
    group = 'moddev'
    description = 'Run the Fabric client from the root project.'
    dependsOn(':fabric:runClient')
}

tasks.register('runServer') {
    group = 'moddev'
    description = 'Run the Fabric server from the root project.'
    dependsOn(':fabric:runServer')
}
