org.gradle.jvmargs=-Xmx8G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
active_mc=26.1.2

minecraft_version=26.1.2

mod_id=voxelbridge
mod_name=VoxelBridge
mod_license=MIT
mod_version=1.0.4
mod_group_id=com.voxelbridge
mod_authors=Gluten King
mod_description=Exports Minecraft and modded content into glTF: blocks, fluids, connected textures, entities, and block entities.
